SET SERVEROUTPUT ON
DECLARE
    MI_EXCEP EXCEPTION;
    PRAGMA EXCEPTION_INIT(MI_EXCEP, -937);
    V1 NUMBER;
    V2 NUMBER;
    
BEGIN
    SELECT EMPLOYEE_ID, SUM(SALARY) INTO V1, V2 FROM EMPLOYEES;
    -- SELECT EMPLOYEE_ID INTO V1 FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
    DBMS_OUTPUT.PUT_LINE(V1);
    
    EXCEPTION
        WHEN MI_EXCEP THEN
            DBMS_OUTPUT.PUT_LINE('Función incorrecta');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error ines');
END;