SET SERVEROUTPUT ON
DECLARE
    CURSOR C1 IS SELECT * FROM REGIONS;
    V1 REGIONS%ROWTYPE;
BEGIN
    OPEN C1;
    FETCH c1 INTO v1;
    
    DBMS_OUTPUT.PUT_LINE(V1.REGION_NAME);
    
    FETCH c1 INTO v1;
    DBMS_OUTPUT.PUT_LINE(V1.REGION_NAME);
    CLOSE C1;
END;